### ISSUE TITLE
Stop on hover for Autoplay mode

### ISSUE THREAD

**Issue by Quadrosh** [mihnsen/ui-carousel#26]
Could you please point me how to do it?
Slick has this feature by default, which is make sense.

**Comment by olyjosh** [comment]
Please, any documentation on how to use this ?

**Comment by olyjosh** [comment]
Is this like hoodwinking us because I did't see anything like pause in the option for this module. And I have asked for documentation on how to pause on mouse hover but no response and that make me feel like you are playing on this
