### ISSUE TITLE
how to access controller scope in <carousel item> tag

### ISSUE THREAD

**Issue by Assdi** [mihnsen/ui-carousel#34]
e.g 
                  `<ui-carousel 
                    slides="vm.independentQuizes"
                    slides-to-show="4"
                    slides-to-scroll="4"
                     on-init="vm.onCarouselInit()"
                    on-before-change="vm.before()"
                    on-after-change="vm.yo(currentSlide)">
                    <carousel-item>
                        <div class="multiple-items">
                        <figure>
                            <div class="editholder">
                                <a href="#/start/{{item.Id}}"><img ng-src="{{resources_url + item.CoverPicPath }}" 
                                        class="img-responsive" alt="">
                               </a>
                            </div>
                             <figcaption>
                                <p>Quiz {{vm.as}}</p> 
                                <h2 class="category">{{item.Name}} </h2>
                            </figcaption>
                        </figure>
                    </div>   
                    </carousel-item>`

 I want to access vm.as in item tag

**Comment by ccasad** [comment]
Same here. Is this not supported?

**Comment by Assdi** [comment]
quick solution is to push the controller object in slides object

**Comment by mcelligottnick** [comment]
I nicer option is to add another directive scope prop, and pass your scope into there. In `https://github.com/mihnsen/ui-carousel/blob/master/src/ui-carousel/directives/carousel.directive.js` where it defines the scope, add another key like `scope: '='`.

Then when using the directive pass in your scope (or any other object your want, really);

`<ui-carousel ... scope='$scope'>`

Then inside the item you can use it as `ctrl.scope.yourScopeProp`.

**Comment by martinmanzo** [comment]
@Assdi how can I do that?

**Comment by Assdi** [comment]
e.g if u have obj vm.solution (in controller) and u want to access it in carousel html then u can push the vm.solution into carousel object. In above case 
I have pushed into slides="vm.independentQuizes"

**Comment by martinmanzo** [comment]
Yeah I was doing that but needed to access a function in my controller from the crousel-item to display some info and could do that. I ended up preprocessing the items to show in order to load the info to the objects as a property.

Anyway, thanks for your time to respond!!

**Comment by Assdi** [comment]
now i stuck in problem I have to call controller function here :( @martinmanzo

**Comment by Assdi** [comment]
yahoo Ive done that :+1:

**Comment by illuska812** [comment]
How?

**Comment by Assdi** [comment]
same solution :D push the function reference into slide obj . just i did above for controller scope @illuska812
`$scope.myFunction=function(){console.log('hi')}`
and push this function ref into slide obj like this 
vm.slides.myfunc=myFunction
