### ISSUE TITLE
Function defined on on-init is not working

### ISSUE THREAD

**Issue by aparnacyanam** [mihnsen/ui-carousel#4]
I have been using your package to add a carousel.When I load my page, entire page loads first and then after less than 2 secs, the carousel appears.So I wanted to add a loading spinner so that when the carousel is ready, the entire page loads up with no sudden appearance of the carousel.In my controller code, I have initialized a variable with true and want to change that value to false when the carousel is ready.I have added on-init="onCarouselReady()" in html and defined the same function in controller.But looks like the function is not even called.Would you please help me in fixing this and let me know if I am missing anything.

**Comment by mihnsen** [comment]
I realize that the onInit is called too soon. I've update package and move onInit to after the track is successful initialize. Here is the pen http://codepen.io/mihnsen/pen/ZejQBJ

**Comment by mihnsen** [comment]
Looks like it solved, close now. Could be reopen later
