### ISSUE TITLE
Uninitialized slide object

### ISSUE THREAD

**Issue by f10l** [mihnsen/ui-carousel#7]
Hi,

sorry for the second issu. I thought it might be good to split, since for this, I don't even know if it is a real bug.

I would like to use json objects as slide array for having the possibility of image description.

I modified your codepen for this:
http://codepen.io/anon/pen/WpVbRQ

When opening first time, it gives an error in the console:
`http://s.codepen.io/boomerang/iFrameKey-4828c091-8050-7970-2dc8-5a293168080d/%7B%7B%20item.url%20%7D%7D 404 (Not Found)`
So I guess the *item.url* is not yet initialized.

Thanks again and best regards,
Fabian

**Comment by tarkant** [comment]
Try to use `ng-src=""` instead of `src=""` and that error will eventually disappear.
Cheers.

**Comment by f10l** [comment]
Thanks a lot! 
It seems to be working with that

**Comment by mihnsen** [comment]
It seems like this issue not related to ui-carousel. close now.
