### ISSUE TITLE
Angular JS 1.3.20 doesn't work

### ISSUE THREAD

**Issue by michelem09** [mihnsen/ui-carousel#9]
It seems this module won't work with 1.3.20, I didn't receive any error but the `slides` property won't get filled. So I always ended up with an empty carousel.
I tried several things also to log from the module but it seems `slides` array remains always empty.

**Comment by lhristov** [comment]
Same here. In the demo codepen, if one replaces the Angular with this https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.19/angular.min.js
it is not initialized.

**Comment by michelem09** [comment]
I can confirm there is a problem with AngularJS < 1.4
I just update my AngularJS to 1.4.14 and the ui-carousel now works fine.

**Comment by mihnsen** [comment]
@michelem09 Fixed on 822763c

**Comment by michelem09** [comment]
Thanks but I can't test it anymore. I'm closing it.
